// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateAutomationFromTemplate(arg1, arg2) {
  return window['go']['ui']['App']['CreateAutomationFromTemplate'](arg1, arg2);
}

export function DeleteAutomation(arg1) {
  return window['go']['ui']['App']['DeleteAutomation'](arg1);
}

export function DeleteSession(arg1) {
  return window['go']['ui']['App']['DeleteSession'](arg1);
}

export function ExecuteAutomation(arg1, arg2) {
  return window['go']['ui']['App']['ExecuteAutomation'](arg1, arg2);
}

export function GetAutomation(arg1) {
  return window['go']['ui']['App']['GetAutomation'](arg1);
}

export function GetAutomationCategories() {
  return window['go']['ui']['App']['GetAutomationCategories']();
}

export function GetAutomationTags() {
  return window['go']['ui']['App']['GetAutomationTags']();
}

export function GetAutomationTemplates() {
  return window['go']['ui']['App']['GetAutomationTemplates']();
}

export function GetAutomations() {
  return window['go']['ui']['App']['GetAutomations']();
}

export function GetProviders() {
  return window['go']['ui']['App']['GetProviders']();
}

export function GetSessions() {
  return window['go']['ui']['App']['GetSessions']();
}

export function LoadSession(arg1) {
  return window['go']['ui']['App']['LoadSession'](arg1);
}

export function OnShutdown(arg1) {
  return window['go']['ui']['App']['OnShutdown'](arg1);
}

export function OnStartup(arg1, arg2) {
  return window['go']['ui']['App']['OnStartup'](arg1, arg2);
}

export function SaveAutomation(arg1) {
  return window['go']['ui']['App']['SaveAutomation'](arg1);
}

export function SaveSession(arg1) {
  return window['go']['ui']['App']['SaveSession'](arg1);
}

export function SendTask(arg1) {
  return window['go']['ui']['App']['SendTask'](arg1);
}

export function StopTask() {
  return window['go']['ui']['App']['StopTask']();
}

export function TestProvider(arg1) {
  return window['go']['ui']['App']['TestProvider'](arg1);
}
