// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetProviders() {
  return window['go']['ui']['App']['GetProviders']();
}

export function GetSessions() {
  return window['go']['ui']['App']['GetSessions']();
}

export function LoadSession(arg1) {
  return window['go']['ui']['App']['LoadSession'](arg1);
}

export function OnShutdown(arg1) {
  return window['go']['ui']['App']['OnShutdown'](arg1);
}

export function OnStartup(arg1, arg2) {
  return window['go']['ui']['App']['OnStartup'](arg1, arg2);
}

export function SaveSession(arg1) {
  return window['go']['ui']['App']['SaveSession'](arg1);
}

export function SendTask(arg1) {
  return window['go']['ui']['App']['SendTask'](arg1);
}

export function StopTask() {
  return window['go']['ui']['App']['StopTask']();
}
