// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddContextBucketItem(arg1) {
  return window['go']['ui']['App']['AddContextBucketItem'](arg1);
}

export function AddTask(arg1) {
  return window['go']['ui']['App']['AddTask'](arg1);
}

export function ClearContextBucket() {
  return window['go']['ui']['App']['ClearContextBucket']();
}

export function CreateAutomationFromTemplate(arg1, arg2) {
  return window['go']['ui']['App']['CreateAutomationFromTemplate'](arg1, arg2);
}

export function DeleteAutomation(arg1) {
  return window['go']['ui']['App']['DeleteAutomation'](arg1);
}

export function DeleteContextBucketItem(arg1) {
  return window['go']['ui']['App']['DeleteContextBucketItem'](arg1);
}

export function DeleteSession(arg1) {
  return window['go']['ui']['App']['DeleteSession'](arg1);
}

export function DuplicateAutomation(arg1, arg2) {
  return window['go']['ui']['App']['DuplicateAutomation'](arg1, arg2);
}

export function ExecuteAutomation(arg1, arg2) {
  return window['go']['ui']['App']['ExecuteAutomation'](arg1, arg2);
}

export function ExecuteAutomationViaWebSocket(arg1, arg2) {
  return window['go']['ui']['App']['ExecuteAutomationViaWebSocket'](arg1, arg2);
}

export function ExportContextBucket() {
  return window['go']['ui']['App']['ExportContextBucket']();
}

export function GetAutomation(arg1) {
  return window['go']['ui']['App']['GetAutomation'](arg1);
}

export function GetAutomationCategories() {
  return window['go']['ui']['App']['GetAutomationCategories']();
}

export function GetAutomationHistory(arg1) {
  return window['go']['ui']['App']['GetAutomationHistory'](arg1);
}

export function GetAutomationTags() {
  return window['go']['ui']['App']['GetAutomationTags']();
}

export function GetAutomationTemplates() {
  return window['go']['ui']['App']['GetAutomationTemplates']();
}

export function GetAutomations() {
  return window['go']['ui']['App']['GetAutomations']();
}

export function GetBackendURL() {
  return window['go']['ui']['App']['GetBackendURL']();
}

export function GetContextBucketItems() {
  return window['go']['ui']['App']['GetContextBucketItems']();
}

export function GetContextBucketSummary() {
  return window['go']['ui']['App']['GetContextBucketSummary']();
}

export function GetProviders() {
  return window['go']['ui']['App']['GetProviders']();
}

export function GetScheduledAutomations() {
  return window['go']['ui']['App']['GetScheduledAutomations']();
}

export function GetSessions() {
  return window['go']['ui']['App']['GetSessions']();
}

export function ImportContextBucket(arg1) {
  return window['go']['ui']['App']['ImportContextBucket'](arg1);
}

export function InterruptChat() {
  return window['go']['ui']['App']['InterruptChat']();
}

export function LoadSession(arg1) {
  return window['go']['ui']['App']['LoadSession'](arg1);
}

export function OnShutdown(arg1) {
  return window['go']['ui']['App']['OnShutdown'](arg1);
}

export function OnStartup(arg1, arg2) {
  return window['go']['ui']['App']['OnStartup'](arg1, arg2);
}

export function RedirectChat(arg1) {
  return window['go']['ui']['App']['RedirectChat'](arg1);
}

export function RefinePrompt(arg1, arg2, arg3) {
  return window['go']['ui']['App']['RefinePrompt'](arg1, arg2, arg3);
}

export function RemoveAutomationSchedule(arg1, arg2) {
  return window['go']['ui']['App']['RemoveAutomationSchedule'](arg1, arg2);
}

export function SaveAutomation(arg1) {
  return window['go']['ui']['App']['SaveAutomation'](arg1);
}

export function SaveAutomationFromChat(arg1, arg2) {
  return window['go']['ui']['App']['SaveAutomationFromChat'](arg1, arg2);
}

export function SaveSession(arg1) {
  return window['go']['ui']['App']['SaveSession'](arg1);
}

export function ScheduleAutomation(arg1, arg2, arg3) {
  return window['go']['ui']['App']['ScheduleAutomation'](arg1, arg2, arg3);
}

export function SearchAutomations(arg1, arg2, arg3) {
  return window['go']['ui']['App']['SearchAutomations'](arg1, arg2, arg3);
}

export function SendChatMessage(arg1, arg2, arg3, arg4) {
  return window['go']['ui']['App']['SendChatMessage'](arg1, arg2, arg3, arg4);
}

export function SendTask(arg1) {
  return window['go']['ui']['App']['SendTask'](arg1);
}

export function StopTask() {
  return window['go']['ui']['App']['StopTask']();
}

export function TestProvider(arg1) {
  return window['go']['ui']['App']['TestProvider'](arg1);
}
