// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {ui} from '../models';
import {context} from '../models';
import {backend} from '../models';

export function GetProviders():Promise<Array<ui.Provider>>;

export function GetSessions():Promise<Array<string>>;

export function LoadSession(arg1:string):Promise<void>;

export function OnShutdown(arg1:context.Context):Promise<void>;

export function OnStartup(arg1:context.Context,arg2:backend.PythonManager):Promise<void>;

export function SaveSession(arg1:string):Promise<void>;

export function SendTask(arg1:ui.TaskRequest):Promise<void>;

export function StopTask():Promise<void>;
